CC=gcc 

P1=arv
P2=cmd_linux
P3=shell
P4=vetor_processos

PROGS=$(P1) $(P2) $(P3) $(P4)

all: $(PROGS)

$(P1):
	$(CC) $(P1).c -o $(P1)
$(P2):
	$(CC) $(P2).c -o $(P2) 
$(P3):
	$(CC) $(P3).c -o $(P3) 
$(P4):
	$(CC) $(P4).c -o $(P4) 

clean:
	rm $(PROGS)
